server:
  port: 8080


file:
  upload:
    path:
      windows: D:\\attendance\\images\\
      linux: /home/ubuntu/attendance/images/


logging.level.org.hibernate:
  sql: DEBUG
  type.descriptor.sql.BasicBinder: TRACE

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 30MB

  datasource:
    url: jdbc:mysql://localhost:3306/attendance?serverTimezone=UTC&charsetEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
#    url: jdbc:h2:tcp://localhost/~/attendance;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=true
#    driver-class-name: org.h2.Driver
#    username: sa

#  sql:
#    init:
#      mode: always
#      schema-locations: classpath:schema.sql
#      data-locations: classpath:data.sql

  h2:
    console:
      enabled: true

  jpa:
    generate-ddl: true
    hibernate:
#      ddl-auto: none
      ddl-auto: create-drop
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
#    database: h2
    properties:
      hibernate:
        format_sql: true # SQL 포매팅

# 도메인 테스트를 위한 @EnableJpaAuditing 의 빈이 충돌되어 overriding 합니다.
  main:
    allow-bean-definition-overriding: true

  web:
    resources:
      static-locations: classpath:/image/default/

  redis:
    host: 127.0.0.1
    port: 6379

  jwt:
    secret: U3ByaW5nIERheSBPZmYgYW5kIER1dHkgUHJvamVjdCBCeSBGYXN0IENhbXB1cyBNaW5pIFByb2VqY3QgNCB0ZWFt

  mail:
    host: smtp.gmail.com
    port: 587
    username: jinyngg@gmail.com
    password: ebfrmjupncqpfgcu
    properties:
      mail:
        smtp:
          starttls:
            enable: true
